#!/bin/bash
source $(dirname "$0")/dockr-common
docker container run -it \
    --env R_LIBS=/root/.R/site-library \
    -v $DOCKR_VOLUME:/root/.R/site-library \
    -v $PROJECT_PATH:/package \
    $DOCKR_IMAGE \
    R
